name: Deploy React App to Docker Hub

on:
  push:
    branches:
      - main  # Ejecutar este workflow solo en el branch 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código fuente
      - name: Checkout repository
        uses: actions/checkout@v2

      # Paso 2: Login en Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Paso 3: Construcción de la imagen Docker
      - name: Build Docker image
        run: |
          docker build -t your-dockerhub-username/guias_despliegue:latest demo-reactjs

      # Paso 4: Push de la imagen a Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push your-dockerhub-username/guias_despliegue:latest
